#ifndef INSTANCIAS_H_
#define INSTANCIAS_H_

#define INSTANCIA_MAIN 0

#define INSTANCIA_1J_ 1

#define INSTANCIA_MJ 10
#define INSTANCIA_MJ_LOCAL 11
#define INSTANCIA_MJ_ONLINE 12
#define INSTANCIA_MJ_CPU 13

#define INSTANCIA_MJ_ONLINE_M 20
#define INSTANCIA_MJ_ONLINE_HOST 21
#define INSTANCIA_MJ_ONLINE_JOIN 22

#define INSTANCIA_VOLVER 100


#endif /* INSTANCIAS_H_ */
